### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by korniaud** [LindaMMM/Jeu#1]
Appel en POST pour la connexion.

Si OK -> passage au calendrier
Si KO -> message "l'utilisateur et le mot de passe ne correspondent pas."

Si plusieurs tentatives, message "appelez Linda pour récupérer vos identifiants."

**Comment by LindaMMM** [comment]
voici la réponse d'un Ajax
on aura tjs un code et un message.
le code est 1 -> OK 

Le nombre de tentative sera en session.
Dans le post , j'attend ssoid et pwd.
