### ISSUE TITLE
Jours

### ISSUE THREAD

**Issue by korniaud** [LindaMMM/Jeu#2]
GET

Récupération des jours de la base à la connexion.

Liste avec jours passés, le jour en cours, les jours à venir.
Information si le cadeau a été gagné.

**Comment by LindaMMM** [comment]
retour avec code + message +values
voir jours.js

**Comment by LindaMMM** [comment]
Code par jour 
N -> non jouer
P-> perdu
G->Gagne
{"code":1,"message":"Jours charger","value":"{\"id\":\"1\",\"1\":\"P\",\"2\":\"N\",\"3\":\"N\",\"4\":\"N\",\"5\":\"N\",\"6\":\"N\",\"7\":\"N\",\"8\":\"N\",\"9\":\"N\",\"10\":\"N\",\"11\":\"P\",\"12\":\"N\",\"13\":\"N\",\"14\":\"N\",\"15\":\"N\",\"16\":\"N\",\"17\":\"N\",\"18\":\"N\",\"19\":\"N\",\"20\":\"N\",\"21\":\"N\",\"22\":\"N\",\"23\":\"N\",\"24\":\"N\"}"}

**Comment by korniaud** [comment]
Ok je regarde ça ;)
