### ISSUE TITLE
Liste des gagnants

### ISSUE THREAD

**Issue by korniaud** [LindaMMM/Jeu#4]
Récupérations des gagnants

**Comment by LindaMMM** [comment]
exemple de liste des gagnants 👍 
{"code":1,"message":"bien jouer","value":"[{\"libelle\":\"Jour3-1\",\"gagant\":\"JUL\",\"dateGain\":\"2019-11-25\"}]"}

-- pour les compteurs:
$count = UserCtrl::GetCountCadeau();
donne 
[{"nbCadeau":"23","nbCadeauGagner":"1"}]
